version: '3.8'

services:
  db:
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=pokemon
    networks:
      - pokemon-network
